# Anti-UAV RGBT dataset - visible modality only
# YOLOv5 data configuration
path: /scratch-shared/glevybirkental/prepared_dataset/visible_fog_i02_beta0.07_A0.30
train: images/train
val:   images/val
test:  images/test
# Classes
nc: 1
names:
  - uav
